/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leoyochi
 */
public class PanelRolUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelRolUsuario
     */
    public PanelRolUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarRol = new javax.swing.JButton();
        btnEditarRol = new javax.swing.JButton();
        btnEliminarRol = new javax.swing.JButton();
        btnNuevoRol = new javax.swing.JButton();
        btnSalirRol = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRolUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIDRol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarRol = new javax.swing.JButton();
        txtTipoRol = new javax.swing.JTextField();
        txtDescripción = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 102));

        btnBuscarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/3643762-find-glass-magnifying-search-zoom_113420.png"))); // NOI18N
        btnBuscarRol.setText("Buscar");
        btnBuscarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRolActionPerformed(evt);
            }
        });

        btnEditarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/3643749-edit-pen-pencil-write-writing_113397.png"))); // NOI18N
        btnEditarRol.setText("Editar");
        btnEditarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRolActionPerformed(evt);
            }
        });

        btnEliminarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trash_delete_remove_icon_143675.png"))); // NOI18N
        btnEliminarRol.setText("Eliminar");
        btnEliminarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRolActionPerformed(evt);
            }
        });

        btnNuevoRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add_circle_create_expand_new_plus_icon_123218.png"))); // NOI18N
        btnNuevoRol.setText("Nuevo");
        btnNuevoRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRolActionPerformed(evt);
            }
        });

        btnSalirRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/4115235-exit-logout-sign-out_114030.png"))); // NOI18N
        btnSalirRol.setText("Salir");

        tablaRolUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRolUsuario);

        jLabel1.setText("ID Rol Usuario");

        jLabel2.setText("Tipo Rol Usuario");

        jLabel3.setText("Descripción Rol Usuario");

        btnRegistrarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/4213460-account-avatar-head-person-profile-user_115386.png"))); // NOI18N
        btnRegistrarRol.setText("Registrar");
        btnRegistrarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtIDRol, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripción, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRegistrarRol)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarRol)
                .addGap(18, 18, 18)
                .addComponent(btnEditarRol)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnNuevoRol)
                .addGap(18, 18, 18)
                .addComponent(btnSalirRol)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRol)
                    .addComponent(btnEditarRol)
                    .addComponent(btnEliminarRol)
                    .addComponent(btnNuevoRol)
                    .addComponent(btnSalirRol)
                    .addComponent(btnRegistrarRol))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDRol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripción, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoRolActionPerformed

    private void btnEliminarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarRolActionPerformed

    private void btnEditarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarRolActionPerformed

    private void btnBuscarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRolActionPerformed

    private void btnRegistrarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarRol;
    public javax.swing.JButton btnEditarRol;
    public javax.swing.JButton btnEliminarRol;
    public javax.swing.JButton btnNuevoRol;
    public javax.swing.JButton btnRegistrarRol;
    public javax.swing.JButton btnSalirRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaRolUsuario;
    public javax.swing.JTextField txtDescripción;
    public javax.swing.JTextField txtIDRol;
    public javax.swing.JTextField txtTipoRol;
    // End of variables declaration//GEN-END:variables
}
