/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Ferra
 */
public class Panel_Producto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Panel_Producto.class.getName());

    /**
     * Creates new form Panel_Producto
     */
    public Panel_Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Producto = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnRegistar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        Id_Producto = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        Id_Producto1 = new javax.swing.JLabel();
        txtId_Producto1 = new javax.swing.JTextField();
        Id_Producto2 = new javax.swing.JLabel();
        txtNombre_Producto1 = new javax.swing.JTextField();
        Id_Producto3 = new javax.swing.JLabel();
        Id_Producto4 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Producto.setBackground(new java.awt.Color(51, 204, 255));
        Panel_Producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/3643762-find-glass-magnifying-search-zoom_113420.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        Panel_Producto.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/4115235-exit-logout-sign-out_114030.png"))); // NOI18N
        btnSalir.setText("Salir");
        Panel_Producto.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        btnEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/3643749-edit-pen-pencil-write-writing_113397.png"))); // NOI18N
        btnEditar.setText("Editar");
        Panel_Producto.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trash_delete_remove_icon_143675.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        Panel_Producto.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add_circle_create_expand_new_plus_icon_123218.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        Panel_Producto.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        btnRegistar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/4213460-account-avatar-head-person-profile-user_115386.png"))); // NOI18N
        btnRegistar.setText("Registrar");
        Panel_Producto.add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre del Producto", "Precio", "Cantidad", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProducto);

        Panel_Producto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 390, 360));

        Id_Producto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Id_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/compra_carrito_icon_209798.png"))); // NOI18N
        Id_Producto.setText("Nombre del Producto");
        Panel_Producto.add(Id_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        Panel_Producto.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, 30));

        Id_Producto1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Id_Producto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/label-tag_icon-icons.com_56376.png"))); // NOI18N
        Id_Producto1.setText("Categoria");
        Panel_Producto.add(Id_Producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        Panel_Producto.add(txtId_Producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 30));

        Id_Producto2.setBackground(new java.awt.Color(204, 204, 204));
        Id_Producto2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Id_Producto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/box_search_product_ean_barcode_icon_148907.png"))); // NOI18N
        Id_Producto2.setText("Id Producto");
        Panel_Producto.add(Id_Producto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        Panel_Producto.add(txtNombre_Producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        Id_Producto3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Id_Producto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Pricetag_precio_4229.png"))); // NOI18N
        Id_Producto3.setText("Precio ");
        Panel_Producto.add(Id_Producto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        Id_Producto4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Id_Producto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add_circle_create_expand_new_plus_icon_123218.png"))); // NOI18N
        Id_Producto4.setText("Cantidad");
        Panel_Producto.add(Id_Producto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        Panel_Producto.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, 30));
        Panel_Producto.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 30));

        getContentPane().add(Panel_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Panel_Producto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Id_Producto;
    public javax.swing.JLabel Id_Producto1;
    public javax.swing.JLabel Id_Producto2;
    public javax.swing.JLabel Id_Producto3;
    public javax.swing.JLabel Id_Producto4;
    public javax.swing.JPanel Panel_Producto;
    public javax.swing.JTable TablaProducto;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId_Producto1;
    private javax.swing.JTextField txtNombre_Producto1;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
