/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Ferra
 */
public class Vista_Punto_Venta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Punto_Venta.class.getName());

    /**
     * Creates new form Vista_Punto_Venta
     */
    public Vista_Punto_Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Punto_Venta = new javax.swing.JPanel();
        txtPuntodeVenta = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtIdProducto1 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        txtiva = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        txtid2 = new javax.swing.JTextField();
        txtid3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Punto_Venta.setBackground(new java.awt.Color(51, 204, 255));
        Panel_Punto_Venta.setPreferredSize(new java.awt.Dimension(780, 470));
        Panel_Punto_Venta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPuntodeVenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPuntodeVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Punto venta.png"))); // NOI18N
        txtPuntodeVenta.setText("Punto de Venta ");
<<<<<<< HEAD
        Panel_Punto_Venta.add(txtPuntodeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
=======
        Panel_Punto_Venta.add(txtPuntodeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
>>>>>>> 507bdc6 (vista)

        btnNuevo.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        Panel_Punto_Venta.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        btnGenerarVenta.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerarVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/generar venta.png"))); // NOI18N
        btnGenerarVenta.setText("Generar Venta ");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 30));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/total.png"))); // NOI18N
        txtTotal.setText("Total:");
        Panel_Punto_Venta.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 220, 30));

        txtIdProducto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/idp1.png"))); // NOI18N
        txtIdProducto1.setText("Id Producto:");
        Panel_Punto_Venta.add(txtIdProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        txtsubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsubtotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Subtotal.png"))); // NOI18N
        txtsubtotal.setText("Subtotal:");
        Panel_Punto_Venta.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        txtiva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/porcentaje.png"))); // NOI18N
        txtiva.setText("IVA:");
        Panel_Punto_Venta.add(txtiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 220, 30));

        txtid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid2ActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 220, 30));

        txtid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid3ActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 220, 30));

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Precio", "Cantidad", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProducto);

        Panel_Punto_Venta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 390, 360));

        getContentPane().add(Panel_Punto_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid2ActionPerformed

    private void txtid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista_Punto_Venta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_Punto_Venta;
    public javax.swing.JTable TablaProducto;
    public javax.swing.JButton btnGenerarVenta;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel txtIdProducto1;
    public javax.swing.JLabel txtPuntodeVenta;
    public javax.swing.JLabel txtTotal;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtid1;
    public javax.swing.JTextField txtid2;
    public javax.swing.JTextField txtid3;
    public javax.swing.JLabel txtiva;
    public javax.swing.JLabel txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
