/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author leoyochi
 */
public class Vista_PuntoVenta extends javax.swing.JFrame {

    /**
     * Creates new form Vista_PuntoVenta
     */
    public Vista_PuntoVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Punto_Venta = new javax.swing.JPanel();
        txtPuntodeVenta = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        txtTotal1 = new javax.swing.JTextField();
        txtIdProducto1 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        txtiva = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPuntoVenta = new javax.swing.JTable();
        btnDescartar = new javax.swing.JButton();
        btnNuevo2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Punto_Venta.setBackground(new java.awt.Color(0, 153, 153));
        Panel_Punto_Venta.setToolTipText("");
        Panel_Punto_Venta.setPreferredSize(new java.awt.Dimension(816, 470));
        Panel_Punto_Venta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPuntodeVenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPuntodeVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Punto venta.png"))); // NOI18N
        txtPuntodeVenta.setText("Punto de Venta ");
        Panel_Punto_Venta.add(txtPuntodeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add_circle_create_expand_new_plus_icon_123218.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 150, 30));
        btnAgregar.getAccessibleContext().setAccessibleDescription("");

        btnGenerarVenta.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerarVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/generar venta.png"))); // NOI18N
        btnGenerarVenta.setText("Generar Venta ");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, 30));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/total.png"))); // NOI18N
        txtTotal.setText("Total:");
        Panel_Punto_Venta.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        txtTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotal1ActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 220, 30));

        txtIdProducto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/idp1.png"))); // NOI18N
        txtIdProducto1.setText("Id Producto:");
        Panel_Punto_Venta.add(txtIdProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        txtsubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsubtotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Subtotal.png"))); // NOI18N
        txtsubtotal.setText("Subtotal:");
        Panel_Punto_Venta.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        txtiva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/porcentaje.png"))); // NOI18N
        txtiva.setText("IVA:");
        Panel_Punto_Venta.add(txtiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 220, 30));

        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 220, 30));

        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });
        Panel_Punto_Venta.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 220, 30));

        tablaPuntoVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPuntoVenta);

        Panel_Punto_Venta.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 400, 320));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 204));
        btnDescartar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trash_delete_remove_icon_143675.png"))); // NOI18N
        btnDescartar.setText("Descartar");
        Panel_Punto_Venta.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));

        btnNuevo2.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nuevo.png"))); // NOI18N
        btnNuevo2.setText("Nuevo");
        Panel_Punto_Venta.add(btnNuevo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Punto_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_Punto_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    private void txtTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal1ActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_PuntoVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_Punto_Venta;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnDescartar;
    public javax.swing.JButton btnGenerarVenta;
    public javax.swing.JButton btnNuevo2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablaPuntoVenta;
    public javax.swing.JLabel txtIdProducto1;
    public javax.swing.JTextField txtIva;
    public javax.swing.JLabel txtPuntodeVenta;
    public javax.swing.JTextField txtSubtotal;
    public javax.swing.JLabel txtTotal;
    public javax.swing.JTextField txtTotal1;
    public javax.swing.JTextField txtid1;
    public javax.swing.JLabel txtiva;
    public javax.swing.JLabel txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
